# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af42bc66e9f6cf13c7ccbe750c1de8edeeee58c400806cfe175aa31c2ed801469180b72473c1c843834e61dc6b8f4d4e94a652eebace3dbc777249f3658a0c6c

test:
  secret_key_base: 196cafb8d37562b94d0c02d1801b833b57044b235d17d275c537782215d754cbe2cb4120b0740bde87750ef249952c1c6b05c135359743d55758a0475c4fe256

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
